# canonical skill -> ways it can appear in a job description
SKILLS = {
    "python": ["python"],
    "java": ["java"],
    "javascript": ["javascript", "js", "ecmascript"],
    "typescript": ["typescript"],
    "c++": ["c++", "cpp"],
    "c#": ["c#", "csharp"],
    "c": ["c programming", "c language"],
    "go": ["golang"],
    "sql": ["sql"],
    "mysql": ["mysql"],
    "postgresql": ["postgresql", "postgres"],
    "mongodb": ["mongodb", "mongo"],
    "redis": ["redis"],
    "nosql": ["nosql"],
    "html": ["html", "html5"],
    "css": ["css", "css3"],
    "react": ["react", "react.js", "reactjs"],
    "angular": ["angular"],
    "vue": ["vue", "vue.js"],
    "tailwind": ["tailwind", "tailwindcss"],
    "node.js": ["node.js", "nodejs", "node"],
    "express": ["express", "express.js"],
    "fastapi": ["fastapi"],
    "django": ["django"],
    "flask": ["flask"],
    "spring boot": ["spring boot", "springboot", "spring"],
    "rest api": ["rest", "rest api", "restful", "restful apis"],
    "graphql": ["graphql"],
    "git": ["git", "github", "gitlab"],
    "docker": ["docker", "containers", "containerization"],
    "kubernetes": ["kubernetes", "k8s"],
    "aws": ["aws", "amazon web services"],
    "azure": ["azure"],
    "gcp": ["gcp", "google cloud"],
    "firebase": ["firebase"],
    "terraform": ["terraform"],
    "ci/cd": ["ci/cd", "cicd", "continuous integration", "github actions", "jenkins"],
    "linux": ["linux", "unix"],
    "machine learning": ["machine learning", "ml"],
    "deep learning": ["deep learning"],
    "nlp": ["nlp", "natural language processing"],
    "pytorch": ["pytorch"],
    "tensorflow": ["tensorflow"],
    "scikit-learn": ["scikit-learn", "sklearn"],
    "pandas": ["pandas"],
    "numpy": ["numpy"],
    "data structures": ["data structures", "dsa"],
    "algorithms": ["algorithms"],
    "oop": ["oop", "object-oriented", "object oriented"],
    "system design": ["system design"],
    "microservices": ["microservices"],
    "testing": ["unit testing", "jest", "pytest", "junit"],
    "agile": ["agile", "scrum"],
}

ALIAS_TO_CANON = {}
for canon, aliases in SKILLS.items():
    ALIAS_TO_CANON[canon] = canon
    for alias in aliases:
        ALIAS_TO_CANON[alias] = canon