SKILLS = {
    "python",
    "java",
    "javascript",
    "typescript",
    "c",
    "c++",
    "c#",
    "go",
    "rust",
    "html",
    "css",
    "react",
    "angular",
    "vue",
    "node.js",
    "express",
    "fastapi",
    "django",
    "spring",
    "sql",
    "mysql",
    "postgresql",
    "mongodb",
    "redis",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "git",
    "github",
    "linux",
    "machine learning",
    "deep learning",
    "tensorflow",
    "pytorch",
    "pandas",
    "numpy",
    "power bi",
    "tableau",
}

ALIAS_TO_CANON = {
    "js": "javascript",
    "ts": "typescript",
    "node": "node.js",
    "nodejs": "node.js",
    "reactjs": "react",
    "mongo": "mongodb",
    "postgres": "postgresql",
    "k8s": "kubernetes",
    "amazon web services": "aws",
    "google cloud": "gcp",
    "microsoft azure": "azure",
    "ml": "machine learning",
    "dl": "deep learning",
    "powerbi": "power bi",
}

for alias, canonical in ALIAS_TO_CANON.items():
    SKILLS.add(alias)